version: 2.1
 
orbs:
  android: circleci/android@0.2.1
jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Create keystore.properties
          command: printf 'releaseKeyAlias=%s\nreleaseKeyPassword=%s\nreleaseKeyStore=%s\nreleaseStorePassword=%s' \
            $RELEASE_KEY_ALIAS $RELEASE_KEY_PASSWORD $RELEASE_KEYSTORE $RELEASE_STORE_PASSWORD > keystore.properties
      - run:
          name: Decode Android key storeS
          command: echo $KEYSTORE | base64 -d | tee keystore android/keystore > /dev/null
      - run:
          name: Create Google Play Key
          command: echo $GPLAY_SERVICE_ACCOUNT_KEY_JSON | base64 -d | tee google-play-key.json /home/circleci/project/google-play-key.json > /dev/null
      - run:
          name : Check google-play-key
          command: cat /home/circleci/project/google-play-key.json
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./android/gradlew
      - run:
          name: Download Dependencies
          command: ./android/gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./android/gradlew build
      - store_artifacts: 
          path: android/app/build/reports
          destination: reports
      - run:
          name: Run TestsN
          command: ./android/gradlew lint test
      - store_test_results:
          path: android/app/build/test-results
      - run:
          name: Install fastlane first
          command: bundle install
      - run:
          name: Execute fastlane
          command: bundle exec fastlane deploy